"""empty message

Revision ID: 9c1e97ce4509
Revises: b44a9f7791ea
Create Date: 2018-09-28 05:43:32.976892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c1e97ce4509'
down_revision = 'b44a9f7791ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oauth2', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'oauth2')
    # ### end Alembic commands ###
